In [5]:
import numpy as np
a=np.array([11,223,34,34])
print(a)
print(a[1:3])

[ 11 223  34  34]
[223  34]


In [8]:
a=np.array([12,344,44])
print(type(a))
print(a)
print(a.copy())
print(np.__version__)

<class 'numpy.ndarray'>
[ 12 344  44]
[ 12 344  44]
2.2.6


In [16]:
import numpy as q
a=q.array([
    [12,233,3],
           [23,234,4]])
print(a)

[[ 12 233   3]
 [ 23 234   4]]


In [21]:
a=q.array([[[892,2324,34],[34,35,43]],[[12,244,24],[244,24,2]]])
print(a)


[[[ 892 2324   34]
  [  34   35   43]]

 [[  12  244   24]
  [ 244   24    2]]]


In [2]:
import numpy as q
a=q.array((21))
print(a.ndim)
b=q.array([12,344,44])
print(b.ndim)
c=q.array([
    [12,233,3],
           [23,234,4]])
print(c.ndim)
d=q.array([[[892,2324,34],[34,35,43]],[[12,244,24],[244,24,2]]])
print(d.ndim)


0
1
2
3


In [29]:
import numpy as np
x=np.array([12,3,4,4],ndmin=4)
print(x)
print(x.ndim)

[[[[12  3  4  4]]]]
4


In [30]:
a="jatindadwalfromhimachal"
print(a[1:-1:3])

andloic


In [35]:
a=q.array([12,3,4,5,3])
print(a[2])
print(a.ndim)
y=a[3]
x=a[4]
print(y+x)

4
1
8


In [42]:
x=q.array([[244,34,5],[24,44,3]])
print(x[0,2])
print(x[1,2])

5
3


In [69]:
a.linspace(1,10,9,dtype=int,
for i in a:
    
    print(i)

1
1
2
3
4
4
5
6
7


In [ ]:
a=q.array([13,4,343,3])
for i in a:

In [14]:
# import numpy as np
# a=np.array([11,5])
# new=a.reshape(2,5,-1)
             

In [16]:
a=np.array([1,2,3,4,5,6])
th=[0,2]
print(a[th])

[1 3]


In [20]:
a=np.array(['cat',"dog"],dtype="U6")
print(a.dtype)
a=np.array(['cat',"dog"],dtype="U2")
print(a.dtype)

<U6
<U2


In [25]:
from numpy.linalg import inv,det,eig
a=np.array([[1,2],[3,4]])
np.dot(a,a)

print(inv(a),det(a),eig(a))

[[-2.   1. ]
 [ 1.5 -0.5]] -2.0000000000000004 EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


In [29]:
np.save('my _array.npy',a)
np.load('my _array.npy')
np.savetxt('data.csv',a,delimiter=',')
np.genfromtxt('data.csv',delimiter=',')


array([[1., 2.],
       [3., 4.]])

In [39]:
arr=np.array([4,23,4,2])
print(np.isnan(arr))
np.nan_to_num(arr)


[False False False False]


array([ 4, 23,  4,  2])

In [41]:
arr=np.array([4,23,4,2,np.nan])
print(np.isnan(arr).any())
print(np.isnan(arr))
arr=np.nan_to_num(arr)

True
[False False False False  True]
