In [5]:
import numpy as np
a=np.array([11,223,34])
print(a)

[ 11 223  34]


In [11]:
a=np.array([12,344,44])
print(type(a))
print(np.__version__)

<class 'numpy.ndarray'>
2.2.6


In [16]:
import numpy as q
a=q.array([
    [12,233,3],
           [23,234,4]])
print(a)

[[ 12 233   3]
 [ 23 234   4]]


In [21]:
a=q.array([[[892,2324,34],[34,35,43]],[[12,244,24],[244,24,2]]])
print(a)


[[[ 892 2324   34]
  [  34   35   43]]

 [[  12  244   24]
  [ 244   24    2]]]


In [26]:
import numpy as q
a=q.array((21))
print(a.ndim)
b=q.array([12,344,44])
print(b.ndim)
c=q.array([
    [12,233,3],
           [23,234,4]])
print(c.ndim)
d=q.array([[[892,2324,34],[34,35,43]],[[12,244,24],[244,24,2]]])
print(d.ndim)
f=

0
1
2
3


In [29]:
import numpy as np
x=np.array([12,3,4,4],ndmin=4)
print(x)
print(x.ndim)

[[[[12  3  4  4]]]]
4


In [30]:
a="jatindadwalfromhimachal"
print(a[1:-1:3])

andloic


In [35]:
a=q.array([12,3,4,5,3])
print(a[2])
print(a.ndim)
y=a[3]
x=a[4]
print(y+x)

4
1
8


In [42]:
x=q.array([[244,34,5],[24,44,3]])
print(x[0,2])
print(x[1,2])

5
3


In [69]:

for i in a:
    
    print(i)

1
1
2
3
4
4
5
6
7


In [ ]:
a=q.array([13,4,343,3])
for i in a: